<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds - Comprehensive Indian Cities
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->delete();

        $cities = [
            // Maharashtra (state_id = 22) - Major Cities
            ['name' => 'Mumbai', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Pune', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Nagpur', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Thane', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Nashik', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Aurangabad', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Solapur', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Kolhapur', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Amravati', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Navi Mumbai', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Sangli', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Malegaon', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Akola', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Latur', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Dhule', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Ahmednagar', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Chandrapur', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Parbhani', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Jalgaon', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Bhiwandi', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Panvel', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Nanded', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Satara', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Ratnagiri', 'state_id' => 22, 'is_active' => 1],
            ['name' => 'Yavatmal', 'state_id' => 22, 'is_active' => 1],

            // Karnataka (state_id = 17) - Major Cities
            ['name' => 'Bangalore', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Mysore', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Mangalore', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Hubli', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Belgaum', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Gulbarga', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Davangere', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Bellary', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Bijapur', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Shimoga', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Tumkur', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Raichur', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Bidar', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Hospet', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Hassan', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Gadag', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Udupi', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Kolar', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Mandya', 'state_id' => 17, 'is_active' => 1],
            ['name' => 'Chikmagalur', 'state_id' => 17, 'is_active' => 1],

            // Delhi (state_id = 10)
            ['name' => 'New Delhi', 'state_id' => 10, 'is_active' => 1],
            ['name' => 'North Delhi', 'state_id' => 10, 'is_active' => 1],
            ['name' => 'South Delhi', 'state_id' => 10, 'is_active' => 1],
            ['name' => 'East Delhi', 'state_id' => 10, 'is_active' => 1],
            ['name' => 'West Delhi', 'state_id' => 10, 'is_active' => 1],
            ['name' => 'Central Delhi', 'state_id' => 10, 'is_active' => 1],
            ['name' => 'North East Delhi', 'state_id' => 10, 'is_active' => 1],
            ['name' => 'North West Delhi', 'state_id' => 10, 'is_active' => 1],
            ['name' => 'South East Delhi', 'state_id' => 10, 'is_active' => 1],
            ['name' => 'South West Delhi', 'state_id' => 10, 'is_active' => 1],
            ['name' => 'Shahdara', 'state_id' => 10, 'is_active' => 1],

            // Tamil Nadu (state_id = 35)
            ['name' => 'Chennai', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Coimbatore', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Madurai', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Tiruchirappalli', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Salem', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Tirunelveli', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Tiruppur', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Vellore', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Erode', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Thoothukkudi', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Dindigul', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Thanjavur', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Ranipet', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Sivakasi', 'state_id' => 35, 'is_active' => 1],
            ['name' => 'Karur', 'state_id' => 35, 'is_active' => 1],

            // Uttar Pradesh (state_id = 38)
            ['name' => 'Lucknow', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Kanpur', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Ghaziabad', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Agra', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Meerut', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Varanasi', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Allahabad', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Bareilly', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Aligarh', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Moradabad', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Saharanpur', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Gorakhpur', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Noida', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Firozabad', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Jhansi', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Muzaffarnagar', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Mathura', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Rampur', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Shahjahanpur', 'state_id' => 38, 'is_active' => 1],
            ['name' => 'Farrukhabad', 'state_id' => 38, 'is_active' => 1],

            // Gujarat (state_id = 12)
            ['name' => 'Ahmedabad', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Surat', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Vadodara', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Rajkot', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Bhavnagar', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Jamnagar', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Junagadh', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Gandhinagar', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Anand', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Navsari', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Morbi', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Nadiad', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Surendranagar', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Bharuch', 'state_id' => 12, 'is_active' => 1],
            ['name' => 'Vapi', 'state_id' => 12, 'is_active' => 1],

            // Rajasthan (state_id = 33)
            ['name' => 'Jaipur', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Jodhpur', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Kota', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Bikaner', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Udaipur', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Ajmer', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Bhilwara', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Alwar', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Bharatpur', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Pali', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Barmer', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Sikar', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Tonk', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Sadulpur', 'state_id' => 33, 'is_active' => 1],
            ['name' => 'Sawai Madhopur', 'state_id' => 33, 'is_active' => 1],

            // West Bengal (state_id = 41)
            ['name' => 'Kolkata', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Howrah', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Durgapur', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Asansol', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Siliguri', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Bardhaman', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Malda', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Baharampur', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Habra', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Kharagpur', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Shantipur', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Dankuni', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Dhulian', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Ranaghat', 'state_id' => 41, 'is_active' => 1],
            ['name' => 'Haldia', 'state_id' => 41, 'is_active' => 1],

            // Telangana (state_id = 36)
            ['name' => 'Hyderabad', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Warangal', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Nizamabad', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Khammam', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Karimnagar', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Ramagundam', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Mahabubnagar', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Nalgonda', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Adilabad', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Suryapet', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Siddipet', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Miryalaguda', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Jagtial', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Mancherial', 'state_id' => 36, 'is_active' => 1],
            ['name' => 'Nirmal', 'state_id' => 36, 'is_active' => 1],

            // Andhra Pradesh (state_id = 2)
            ['name' => 'Visakhapatnam', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Vijayawada', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Guntur', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Nellore', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Kurnool', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Rajahmundry', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Kakinada', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Tirupati', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Anantapur', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Kadapa', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Vizianagaram', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Eluru', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Ongole', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Nandyal', 'state_id' => 2, 'is_active' => 1],
            ['name' => 'Machilipatnam', 'state_id' => 2, 'is_active' => 1],

            // Kerala (state_id = 19)
            ['name' => 'Thiruvananthapuram', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Kochi', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Kozhikode', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Kollam', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Thrissur', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Palakkad', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Alappuzha', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Malappuram', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Ponnani', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Vatakara', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Kanhangad', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Payyanur', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Koyilandy', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Kannur', 'state_id' => 19, 'is_active' => 1],
            ['name' => 'Thalassery', 'state_id' => 19, 'is_active' => 1],

            // Punjab (state_id = 32)
            ['name' => 'Ludhiana', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Amritsar', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Jalandhar', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Patiala', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Bathinda', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Mohali', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Pathankot', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Hoshiarpur', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Batala', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Moga', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Malerkotla', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Khanna', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Phagwara', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Muktsar', 'state_id' => 32, 'is_active' => 1],
            ['name' => 'Barnala', 'state_id' => 32, 'is_active' => 1],

            // Haryana (state_id = 13)
            ['name' => 'Faridabad', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Gurgaon', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Panipat', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Ambala', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Yamunanagar', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Rohtak', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Hisar', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Karnal', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Sonipat', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Panchkula', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Bhiwani', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Sirsa', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Bahadurgarh', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Jind', 'state_id' => 13, 'is_active' => 1],
            ['name' => 'Thanesar', 'state_id' => 13, 'is_active' => 1],

            // Bihar (state_id = 5)
            ['name' => 'Patna', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Gaya', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Bhagalpur', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Muzaffarpur', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Darbhanga', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Arrah', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Begusarai', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Katihar', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Munger', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Chhapra', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Purnia', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Saharsa', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Sasaram', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Hajipur', 'state_id' => 5, 'is_active' => 1],
            ['name' => 'Dehri', 'state_id' => 5, 'is_active' => 1],

            // Madhya Pradesh (state_id = 21)
            ['name' => 'Indore', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Bhopal', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Jabalpur', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Gwalior', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Ujjain', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Sagar', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Dewas', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Satna', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Ratlam', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Rewa', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Murwara', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Singrauli', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Burhanpur', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Khandwa', 'state_id' => 21, 'is_active' => 1],
            ['name' => 'Morena', 'state_id' => 21, 'is_active' => 1],

            // Jharkhand (state_id = 16)
            ['name' => 'Ranchi', 'state_id' => 16, 'is_active' => 1],
            ['name' => 'Jamshedpur', 'state_id' => 16, 'is_active' => 1],
            ['name' => 'Dhanbad', 'state_id' => 16, 'is_active' => 1],
            ['name' => 'Bokaro', 'state_id' => 16, 'is_active' => 1],
            ['name' => 'Deoghar', 'state_id' => 16, 'is_active' => 1],
            ['name' => 'Phusro', 'state_id' => 16, 'is_active' => 1],
            ['name' => 'Hazaribagh', 'state_id' => 16, 'is_active' => 1],
            ['name' => 'Giridih', 'state_id' => 16, 'is_active' => 1],
            ['name' => 'Ramgarh', 'state_id' => 16, 'is_active' => 1],
            ['name' => 'Medininagar', 'state_id' => 16, 'is_active' => 1],
            ['name' => 'Chirkunda', 'state_id' => 16, 'is_active' => 1],

            // Odisha (state_id = 29)
            ['name' => 'Bhubaneswar', 'state_id' => 29, 'is_active' => 1],
            ['name' => 'Cuttack', 'state_id' => 29, 'is_active' => 1],
            ['name' => 'Rourkela', 'state_id' => 29, 'is_active' => 1],
            ['name' => 'Brahmapur', 'state_id' => 29, 'is_active' => 1],
            ['name' => 'Sambalpur', 'state_id' => 29, 'is_active' => 1],
            ['name' => 'Puri', 'state_id' => 29, 'is_active' => 1],
            ['name' => 'Balasore', 'state_id' => 29, 'is_active' => 1],
            ['name' => 'Bhadrak', 'state_id' => 29, 'is_active' => 1],
            ['name' => 'Baripada', 'state_id' => 29, 'is_active' => 1],
            ['name' => 'Jharsuguda', 'state_id' => 29, 'is_active' => 1],

            // Chhattisgarh (state_id = 7)
            ['name' => 'Raipur', 'state_id' => 7, 'is_active' => 1],
            ['name' => 'Bhilai', 'state_id' => 7, 'is_active' => 1],
            ['name' => 'Bilaspur', 'state_id' => 7, 'is_active' => 1],
            ['name' => 'Korba', 'state_id' => 7, 'is_active' => 1],
            ['name' => 'Durg', 'state_id' => 7, 'is_active' => 1],
            ['name' => 'Rajnandgaon', 'state_id' => 7, 'is_active' => 1],
            ['name' => 'Raigarh', 'state_id' => 7, 'is_active' => 1],
            ['name' => 'Jagdalpur', 'state_id' => 7, 'is_active' => 1],
            ['name' => 'Ambikapur', 'state_id' => 7, 'is_active' => 1],
            ['name' => 'Chirmiri', 'state_id' => 7, 'is_active' => 1],

            // Assam (state_id = 4)
            ['name' => 'Guwahati', 'state_id' => 4, 'is_active' => 1],
            ['name' => 'Silchar', 'state_id' => 4, 'is_active' => 1],
            ['name' => 'Dibrugarh', 'state_id' => 4, 'is_active' => 1],
            ['name' => 'Jorhat', 'state_id' => 4, 'is_active' => 1],
            ['name' => 'Nagaon', 'state_id' => 4, 'is_active' => 1],
            ['name' => 'Tinsukia', 'state_id' => 4, 'is_active' => 1],
            ['name' => 'Tezpur', 'state_id' => 4, 'is_active' => 1],
            ['name' => 'Bongaigaon', 'state_id' => 4, 'is_active' => 1],
            ['name' => 'Dhubri', 'state_id' => 4, 'is_active' => 1],
            ['name' => 'Diphu', 'state_id' => 4, 'is_active' => 1],

            // Uttarakhand (state_id = 39)
            ['name' => 'Dehradun', 'state_id' => 39, 'is_active' => 1],
            ['name' => 'Haridwar', 'state_id' => 39, 'is_active' => 1],
            ['name' => 'Roorkee', 'state_id' => 39, 'is_active' => 1],
            ['name' => 'Haldwani', 'state_id' => 39, 'is_active' => 1],
            ['name' => 'Rudrapur', 'state_id' => 39, 'is_active' => 1],
            ['name' => 'Kashipur', 'state_id' => 39, 'is_active' => 1],
            ['name' => 'Rishikesh', 'state_id' => 39, 'is_active' => 1],
            ['name' => 'Pithoragarh', 'state_id' => 39, 'is_active' => 1],

            // Himachal Pradesh (state_id = 14)
            ['name' => 'Shimla', 'state_id' => 14, 'is_active' => 1],
            ['name' => 'Mandi', 'state_id' => 14, 'is_active' => 1],
            ['name' => 'Solan', 'state_id' => 14, 'is_active' => 1],
            ['name' => 'Nahan', 'state_id' => 14, 'is_active' => 1],
            ['name' => 'Sundarnagar', 'state_id' => 14, 'is_active' => 1],
            ['name' => 'Palampur', 'state_id' => 14, 'is_active' => 1],

            // Jammu and Kashmir (state_id = 15)
            ['name' => 'Srinagar', 'state_id' => 15, 'is_active' => 1],
            ['name' => 'Jammu', 'state_id' => 15, 'is_active' => 1],
            ['name' => 'Anantnag', 'state_id' => 15, 'is_active' => 1],
            ['name' => 'Baramulla', 'state_id' => 15, 'is_active' => 1],
            ['name' => 'Sopore', 'state_id' => 15, 'is_active' => 1],
            ['name' => 'Kathua', 'state_id' => 15, 'is_active' => 1],

            // Goa (state_id = 11)
            ['name' => 'Panaji', 'state_id' => 11, 'is_active' => 1],
            ['name' => 'Margao', 'state_id' => 11, 'is_active' => 1],
            ['name' => 'Vasco da Gama', 'state_id' => 11, 'is_active' => 1],
            ['name' => 'Mapusa', 'state_id' => 11, 'is_active' => 1],
            ['name' => 'Ponda', 'state_id' => 11, 'is_active' => 1],

            // Chandigarh (state_id = 6)
            ['name' => 'Chandigarh', 'state_id' => 6, 'is_active' => 1],

            // Pondicherry (state_id = 31)
            ['name' => 'Puducherry', 'state_id' => 31, 'is_active' => 1],
            ['name' => 'Karaikal', 'state_id' => 31, 'is_active' => 1],
            ['name' => 'Yanam', 'state_id' => 31, 'is_active' => 1],
            ['name' => 'Mahe', 'state_id' => 31, 'is_active' => 1],
        ];

        foreach ($cities as $city) {
            DB::table('cities')->insert([
                'name' => $city['name'],
                'state_id' => $city['state_id'],
                'is_active' => $city['is_active'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}